### PR TITLE
hello microverse project

### PR DESCRIPTION
**Pull request by maths29**
in this project:
 I updated the style.css and
I added the linter files and readme file
I also add text.md file to git ignore

### CODE REVIEW

**Review by ridwanediallo — CHANGES_REQUESTED** [review]
# Changes Required ♻️
## Hi @maths29 , 
AlmostThereReachGIF

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- GitHub flow is used correctly. ✔
- All linters checks are ok. ✔


## Required Changes ♻️

- [ ] So far, so good :+1: . However, there are a few more requirements to complete this project. Please make every effort to work on them. :ok_hand: 
### Add:

1.   Screenshot from 2023-04-25 16-51-30

2. Screenshot from 2023-04-25 16-52-41

- [ ] Please ignore the `test.md` file after adding it to the `gitignore` file because it is an unnecessary file that we do not need to push. You may wonder why it is included if it is unnecessary. The answer is that the goal of doing so is to show you that whenever you have such a file, you should ignore it and not push it to your github repo. :ok_hand:   😊


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by usorfaitheloho — CHANGES_REQUESTED** [review]
Hi @maths29 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

almost

 ## Highlights :dart: 
 * Your project look really professional :heavy_check_mark:
 * Linter is set up correctly and all linters passed :+1:
 * You follow HTML and CSS best practices :clap:
 * Good PR title and summary :+1: 
 
## Required Changes ♻️
-  As suggested by the previous reviewer, please add the `test.md` file to the `.gitignore` file in your project to practise how to ignore files on Github 😄 


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by wayungi — APPROVED** [review]
Hi @maths29 , 

image

Great work, your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

**Remember: Every finish line 🏁  is the beginning of a new race 🐎** 

## Highlights
- [ ] All linter checks passing ✔️ 
- [ ]  Correct GitHub flow ✔️ 
- [ ] Descriptive PR body ✔️ 

## Optional suggestions
test

- [ ] The `test.md` file is not supposed to be in the repo. Please have it deleted 👍🏾 


branch
- [ ] The branch called **master** was renamed to **main**. You will rarely find `master` in use today. I suggest you rename your branch to `main` 
- [ ] **feature-1** is not descriptive for a branch name. Good branch names describe what features the branch adds to the project. eg **created-sidebar** for a feature branch that adds a side bar to the project



_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by maths29** [comment]
finally got approved

**Pull request merged**
